# Generated by Django 6.0.7 on 2026-07-15 18:25

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('protein_g', models.PositiveIntegerField(default=0)),
                ('carbs_g', models.PositiveIntegerField(default=0)),
                ('fat_g', models.PositiveIntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan'), ('high-protein', 'High Protein'), ('low-carb', 'Low Carb'), ('snack', 'Snack')], max_length=30), blank=True, default=list)),
                ('eaten_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-eaten_at'],
                'indexes': [models.Index(fields=['eaten_at'], name='meals_meal_eaten_a_4eb214_idx'), models.Index(fields=['name'], name='meals_meal_name_a0b94d_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='meals_meal_tags_27769b_gin')],
            },
        ),
    ]
